### ISSUE TITLE
Cannot assing requested address

### ISSUE THREAD

**Issue by ftaplayer** [Nriver/anki-web-server#1]
I tested running the server with the command
$ python app.py

generated the error:

Traceback (most recent call last):
  File "app.py", line 8, in <module>
    from pathlib import Path
ImportError: No module named pathlib

I tested running the server with the command
$ python3 app.py

generated the error:

* Serving Flask app "flaskbp" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "app.py", line 48, in <module>
    app.run(host=listen_IP, port=int(listen_port))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/werkzeug/serving.py", line 987, in run_simple
    s.bind(server_address)
OSError: [Errno 99] Cannot assign requested address

How can I fix it?

**Comment by Nriver** [comment]
Rename ankiweb.conf.sample to ankiweb.conf and modify the configuration to match your environment.

**Comment by ftaplayer** [comment]
I installed anki-web-server. I can see the login page but it is not working. How exactly do I modify ankiweb.conf? Do I have to put the paths of the anki-sync-server files? 

my anki-sync-server is installed in:  /home/ubuntu/anki-sync-server/

The **ankisyncd.conf** file is written like this:

[sync_app]
host = 127.0.0.1
port = 27701
data_root = ./collections
base_url = /sync/
base_media_url = /msync/
auth_db_path = ./auth.db
session_db_path = ./session.dbr

The **ankiweb.conf** file is written like this:

[web_app]
debug = True
listen_IP = 127.0.0.1 **(Is It correct?)**
listen_port = 27702 **(Is It correct?)**
context_path = ankiweb **(What do I put here?)**
secret_key = YOUR_SECRET_KEY **(What do I put here?)**

data_root = . /home/ubuntu/anki-sync-server/collections/ **(Is It correct?)**
base_url = /sync/ **(What do I put here?)**
base_media_url = /msync/ **(What do I put here?)**
auth_db_path = . /home/ubuntu/anki-sync-server/auth.db **(Is It correct?)**
session_db_path = /path/to/anki/session.db **(What do I put here?)**

**Comment by darkmusic** [comment]
@ftaplayer - I had the same questions, but was able to figure this out.
- **listen_IP** - That's the IP address of the network interface you want the server to listen on.  So 127.0.0.1 should be fine in most cases.
- **listen_port** - The anki sync server listens on 27701 by default, which is why this uses the next port, 27702.  But you can choose whatever port you want, as long as it is available.
- **context_path** - This is used for accessing the web sever itself.  In the readme, it says to go to http://127.0.0.1:27002/ankiweb/, so the context_path in this case is what the "ankiweb" portion of the URL means.
- **secret_key** - This is the key that Flask will use to create sessions.  See [here](https://flask.palletsprojects.com/en/1.1.x/quickstart/#sessions).
- **data_root** - Take out the ". " at the beginning and the "/" at the end, but otherwise that should be fine (make sure a collections directory exists at that location)
- **base_url** - Leave alone
- **base_media_url** - Leave alone
- **auth_db_path** - Remove ". " at the beginning, but otherwise should be fine (make sure that the auth.db exists in that location)
- **session_db_path** - This will be the same as the auth_db_path, but point to session_db instead.  Make sure that session.db exists in that location.

Oh and by the way, it isn't clear from the readme, but the website UI is in Chinese.  It does appear to be functional though.
And be sure when you go to the website, you go to http://127.0.0.1:27002/ankiweb/, not http://127.0.0.1:27002/ankiweb.  The trailing slash is important.

**Comment by Nriver** [comment]
If the manual configuration is difficult, you can go to [anki-web-server-docker](https://github.com/Nriver/anki-web-server-docker) for simple deploy with docker.
